# Generated by Django 3.2.8 on 2022-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.FileField(default=0.0010340796690945057, upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='photoo',
            field=models.FileField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
    ]
